### ISSUE TITLE
" Implement 'sample' (and test it) "

### ISSUE THREAD

**Issue by appoll** [openai/gym-http-api#12]
I only have to check that my understanding of the task is correct before submitting a pull request. 
As far as I can see, the picking of a random action from the action space is done by the example agent and that shouldn't be the case. Instead, this should be done on the "server side" by actually using the sample() method available in the action space of the specific environment, assuming the additional endpoint is provided.

**Comment by catherio** [comment]
Yes, correct - an additional endpoint should be created which exposes the "sample" method on the action space. 

To provide a little more context, notice that the interface exposed by this API is as close as possible to the interface exposed by the "Env" class here: https://github.com/openai/gym/blob/master/gym/core.py. What's missing is the interface exposed by the "Space" class in the same file, including "sample" and "contains".

The functionality in gym that already exists, which we would like to expose, is this:
```python
import gym
env = gym.make('CartPole-v0')
env.action_space.sample()
```

Implementing the "contains" method at the same time may be easy to tag on, if you're up for it!

**Comment by appoll** [comment]
Thanks for the elaborate reassurance. As per pr https://github.com/openai/gym-http-api/pull/13, both endpoints are up for review

**Comment by catherio** [comment]
Apologies for letting this linger so long, and thanks for the contribution!
