### ISSUE TITLE
Translate TODOs into issues

### ISSUE THREAD

**Issue by paulhendricks** [openai/gym-http-api#24]
@catherio: Can you shed some light on which of these might be outstanding? If we can translate some of these into issues and sort them, myself and other community members might be able to start to tackle them.

# Looks done (confirmation would be helpful)
* Implement 'sample' (and test it)
* Implement 'contains' (and test it)

# TODO
* Make the directory structure better conform to standard python package structures (http://www.kennethreitz.org/essays/repository-structure-and-python, http://peterdowns.com/posts/first-time-with-pypi.html)
* Docker integration
* Handle ResetNeeded while monitor is active
* Handle APIConnectionError: Unexpected error communicating with OpenAI Gym
* Check: was anything improved by adding session / socket reuse?
* Reports of "broken pipe" errors: reproduce and investigate
* Measure latency/performance. How slow is HTTP, Flask? What is the use case for this implementation, versus a potential future faster ZeroMQ implementation?
* Make remote environments have the same interface as non-remote environments
* Get Travis CI working
* Test all possible environments in integration tests
* Handle the error thrown if the directory isn't cleared for the monitor
* Document the fact that two-monitors-open will cause a problem; be clear that this is meant to be one-client

**Comment by catherio** [comment]
Thanks Paul - I think most of these are actually outdated, but the performance measurement is definitely still something that would be really great to know, so I've made an "enhancement" issue for it.

Many of these TODOs were bugs and weirdnesses that I saw when I first started working on the client - another thing you could do would be to just play around with the code and see if any of these are still active, or if you can break it in any new and confusing ways!
