### ISSUE TITLE
Enhancement: measure latency/performance

### ISSUE THREAD

**Issue by catherio** [openai/gym-http-api#25]
Measure latency/performance. How slow is HTTP, Flask? Under what use patterns is HTTP sufficiently performative, and under what use patterns would a user want a faster implementation, for example using ZeroMQ or similar?

**Comment by stites** [comment]
I couldn't be more enthusiastic about getting some numbers on this. In comparing the native python API to this http-based one, there was a noticeable difference in latency. Has there been any investigation into using something like Thrift, or compiling the gym with Cython and having everything bind off of compiled C?

**Comment by catherio** [comment]
@stites Nothing has been investigated whatsoever! I'd love to hear any thoughts or see any improvements/contributions :)

**Comment by stites** [comment]
Just a followup -- my initial thoughts must have been a blip: I've been using the flask server and it's been performing fine! Unless others are finding speed issues, I think this can be backlogged.

**Comment by catherio** [comment]
Cool! Closing for now.
