### ISSUE TITLE
Maintainer status?

### ISSUE THREAD

**Issue by stites** [openai/gym-http-api#52]
Hey @catherio, thanks for all the work you've put into this. I'm wondering if you could tell me how actively OpenAI plans to maintain this repo. If you are all lacking dev-time maybe putting this project on TravisCI and adding a merge-bot, if a current contributor +1s the PR, could help speed things up? (Seeing as there are currently 13 language bindings, I'd guess that this repo requires more than the current number of developers to ensure stability, anyhow).

**Comment by catherio** [comment]
Hi Sam - you're right that my attention is heavily drawn elsewhere recently. Merge-bot is a great idea. Is there one you like and recommend?

**Comment by stites** [comment]
Not on hand. I'll look into it!

**Comment by stites** [comment]
Yup, so timing didn't work out on this one. I'm closing this ticket for the time being.
